name: Run Semgrep via explicit docker call
description: Run Semgrep via explicit docker call
inputs:
  semgrep-app-token:
    required: true
    description: Semgrep app token
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - run: |
        docker run --rm -v  "${PWD}:/src" \
        -e SEMGREP_APP_TOKEN=${{ inputs.semgrep-app-token }} \
        -e SEMGREP_REPO_NAME=${GITHUB_REPOSITORY} \
        -e SEMGREP_BRANCH=${GITHUB_REF} \
        -e SEMGREP_COMMIT=${{ github.event.pull_request.head.sha }} \
        -e SEMGREP_PR_ID=${{github.event.pull_request.number}} \
        -e SEMGREP_BASELINE_REF='HEAD^' \
        semgrep/semgrep:latest-nonroot \
        semgrep ci
      shell: bash
